### ISSUE TITLE
Strange Behavior in Browser after login and return

### ISSUE THREAD

**Issue by shpeedle** [auth0-blog/gatsby-auth0#1]
Hello, 

Thanks for making this auth0 example.

It seems to work great, however I have some strange behavior in the browser after logging in and returning later.

Problem:
The screen is just blank/white. 

There is an error in the console that says => Failed to load resource: the server responded with a status of 400 ().

Then after a few minutes the screen will load and a warning will appear in the browser that says => React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.

I'll be honest, I'm completely clueless as to what the issue is here.

Thanks in advance!

**Comment by arhoy** [comment]
Yes this does not work! I get the same error. 
For a company that specializes in authentication that is pretty bad.

**Comment by ghost** [comment]
@arhoy I switched to using AWS Amplify/Cognito. It's more complex but it's good stuff. I don't think they pay any attention to this repo :)

**Comment by arhoy** [comment]
Hmm okay thanks @break-paradigm . I just want a simple strategy that works in my Gatsby app. It is ridiculous why this should not be as easy as `hello world` in 2019. Just finished watching a **2 hour** video where an auth0 and Gatsby expert try to get auth to work in an app and still not 100%

**Comment by ghost** [comment]
AWS Amplify works great on a Gatsby site. Check out my demo here: https://www.gatsbyjs.org/starters/ben-siewert/gatsby-starter-auth-aws-amplify/

I think it's pretty solid but I did do it with limited time. Let me know what you think.

**Comment by jmcbee** [comment]
Experiencing the same. Migrated to firebase auth which appears to be easier to setup than this.

**Comment by samjulien** [comment]
Hey everyone, I am so sorry for the delay -- for some reason I've received zero notifications on this repo. 

@ben-siewert, are you still having this problem? Can you provide any more context (versions of React/Gatsby, etc.) or a reproduction/repo to look at? Were you following along with the steps in the tutorial to re-create it or just cloning this repo?

Same questions for you @arhoy.

Thanks and again sorry for the delayed response!

**Comment by shpeedle** [comment]
@samjulien I moved on a long time ago. Thanks for reaching out. 

FYI: I even contacted support and provided them with the link to this repo/issue and asked for help and they didn't do anything but arrange a sales call with me. It was annoying to say the least. I was looking to use auth0 for a client but went with AWS Cognito.

Thanks!

**Comment by samjulien** [comment]
Bummer, sorry to hear that @ben-siewert! I'll take that feedback back to the sales team.

**Comment by kosvrouvas** [comment]
I can still see this I think. It seems that going through pages keeps the auth token, but reloading the page (say when you press Save on VS Code) loses the token and get a 400 Bad Request on the Network tab for auth0.com.

In order to fix it you need to clear your browsers cookies.

Haven't tested on production yet.

See:

https://youtu.be/9fa4k3E2mI0

**Comment by samjulien** [comment]
@kosvrouvas are you using Google as a social login by chance? If so you'll need to get your own keys instead of using the dev ones in order to make the silent auth work. Otherwise, be sure that you have the local address of the app in the "Allowed Web Origins" setting in your Application Settings in Auth0.

**Comment by arhoy** [comment]
@ghost do you have demo gatsby repo or tutorial with the cognito social logins?

**Comment by kosvrouvas** [comment]
@samjulien sorry for the super late reply, no we are not using any social login. localhost is allowed web origin

**Comment by kosvrouvas** [comment]
So yeah well, just found why refreshing the page shows a Bad Request.

The log at manage.auth0.com showed a "Failed Silent Auth The specified redirect_uri 'http://localhost:8000/callback' does not have a registered origin."

After some tinkering I found out that the allowed web origins was http://localhost:8000/ but needs to be http://localhost:8000. Without the trailing slash.

Also mentioned here: https://community.auth0.com/t/silent-authentication-does-not-have-a-registered-origin/8836/3
