### ISSUE TITLE
re: small bug - always redirects to Account page

### ISSUE THREAD

**Issue by osseonews** [auth0-blog/gatsby-auth0#5]
This code is excellent. However, there seems to be a slight bug in this code. In the auth.js on Line 54, you have the code: navigate("/account/")  The problem is that after someone logs in, this causes the app to redirect to the /account/ page no matter what page the user goes to. So after you log in, every single link on the website, simply redirects to /account/ page. We had to comment out this line so that after log in, the pages didn't all redirect to /account/. Is there any way to provide code so that, the /account/ page is navigated to only at the 1st login? Then after the user is logged in, the pages don't all redirect?

**Comment by osseonews** [comment]
I would mention that commenting that line out actually causes the application to break, because then the application has no where to redirect to. So basically, after someone logs in, the only thing they can do is visit the routes under /account/. Every other page outside of these routes simply redirects to the /account/ page. Any idea how to fix this?

**Comment by samjulien** [comment]
@osseonews not sure if you're the same person who I talked with on the Community Forum, but I've created a branch here that corrects this: https://github.com/auth0-blog/gatsby-auth0/tree/sam-update-redirect

I need to get with the Content team about updating the article before I can merge it into master, but that should solve your problem. Thanks!
